name = "adailsontestmds"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "8ddd5cbc-ede0-49f9-9535-2d9469ad2f0c"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
